"""Analyse private Zhang et al. (2022) summary curves without pseudo-replication.

Inputs are the ignored CSV files generated by ``build_zhang_2022_dataset.py``.
Outputs remain private by default. Model-selection statistics are descriptive
because the workbook contains consolidated means rather than reactor trajectories.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import least_squares
from scipy.stats import pearsonr, spearmanr


def modified_gompertz(time: np.ndarray, potential: float, rate: float, lag: float) -> np.ndarray:
    exponent = (np.e * rate / potential) * (lag - time) + 1.0
    return potential * np.exp(-np.exp(np.clip(exponent, -50.0, 50.0)))


def logistic(time: np.ndarray, potential: float, rate: float, lag: float) -> np.ndarray:
    exponent = (4.0 * rate / potential) * (lag - time) + 2.0
    return potential / (1.0 + np.exp(np.clip(exponent, -50.0, 50.0)))


def first_order(time: np.ndarray, potential: float, rate_constant: float) -> np.ndarray:
    return potential * (1.0 - np.exp(-rate_constant * time))


MODELS = {
    "modified_gompertz": (
        modified_gompertz,
        (300.0, 20.0, 3.0),
        (1.0, 1e-4, -20.0),
        (2000.0, 200.0, 30.0),
    ),
    "logistic": (logistic, (300.0, 20.0, 3.0), (1.0, 1e-4, -20.0), (2000.0, 200.0, 30.0)),
    "first_order": (first_order, (350.0, 0.1), (1.0, 1e-5), (5000.0, 10.0)),
}


def _information_criteria(
    observed: np.ndarray, predicted: np.ndarray, parameters: int
) -> dict[str, float]:
    residual = observed - predicted
    n = len(observed)
    rss = max(float(np.sum(residual**2)), np.finfo(float).tiny)
    aic = n * np.log(rss / n) + 2 * parameters
    aicc = aic + (2 * parameters * (parameters + 1)) / (n - parameters - 1)
    bic = n * np.log(rss / n) + parameters * np.log(n)
    return {"aic": float(aic), "aicc": float(aicc), "bic": float(bic)}


def _fit(time: np.ndarray, observed: np.ndarray, model: str) -> dict[str, object]:
    function, initial, lower, upper = MODELS[model]
    solution = least_squares(
        lambda parameters: function(time, *parameters) - observed,
        np.asarray(initial),
        bounds=(np.asarray(lower), np.asarray(upper)),
    )
    predicted = function(time, *solution.x)
    residual = observed - predicted
    rss = float(np.sum(residual**2))
    return {
        "parameters": solution.x,
        "predicted": predicted,
        "rmse": float(np.sqrt(np.mean(residual**2))),
        "mae": float(np.mean(np.abs(residual))),
        "durbin_watson": float(np.sum(np.diff(residual) ** 2) / rss),
        **_information_criteria(observed, predicted, len(initial)),
    }


def _crossing_time(time: np.ndarray, values: np.ndarray, target: float) -> float:
    index = np.flatnonzero(values >= target)
    if not len(index):
        return float("nan")
    right = int(index[0])
    if right == 0:
        return float(time[0])
    left = right - 1
    fraction = (target - values[left]) / (values[right] - values[left])
    return float(time[left] + fraction * (time[right] - time[left]))


def kinetic_metrics(methane: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    required = {"experiment_axis", "treatment", "time_days", "cumulative_methane_ml"}
    missing = required.difference(methane.columns)
    if missing:
        raise ValueError(f"Missing methane columns: {', '.join(sorted(missing))}")
    comparisons: list[dict[str, object]] = []
    treatment_metrics: list[dict[str, object]] = []
    for (axis, treatment), frame in methane.groupby(["experiment_axis", "treatment"], sort=True):
        frame = frame.sort_values("time_days")
        time = frame["time_days"].to_numpy(float)
        observed = frame["cumulative_methane_ml"].to_numpy(float)
        final = float(observed[-1])
        fits = {}
        for model in MODELS:
            fit = _fit(time, observed, model)
            fits[model] = fit
            parameters = fit["parameters"]
            comparisons.append(
                {
                    "experiment_axis": axis,
                    "treatment": treatment,
                    "model": model,
                    "potential_ml": float(parameters[0]),
                    "rate_ml_d": float(parameters[1]) if model != "first_order" else np.nan,
                    "rate_constant_d_1": float(parameters[1]) if model == "first_order" else np.nan,
                    "lag_d": float(parameters[2]) if len(parameters) == 3 else np.nan,
                    "rmse_ml": fit["rmse"],
                    "mae_ml": fit["mae"],
                    "aic": fit["aic"],
                    "aicc": fit["aicc"],
                    "bic": fit["bic"],
                    "durbin_watson": fit["durbin_watson"],
                    "validation_scope": "descriptive_fit_to_consolidated_means",
                }
            )
        gompertz = fits["modified_gompertz"]["parameters"]
        day10 = float(observed[np.flatnonzero(time == 10.0)[0]])
        treatment_metrics.append(
            {
                "experiment_axis": axis,
                "treatment": treatment,
                "final_day": float(time[-1]),
                "final_methane_ml": final,
                "day10_methane_ml": day10,
                "auc_methane_ml_d": float(np.trapezoid(observed, time)),
                "observed_t50_d": _crossing_time(time, observed, 0.5 * final),
                "observed_t90_d": _crossing_time(time, observed, 0.9 * final),
                "gompertz_potential_ml": float(gompertz[0]),
                "gompertz_rate_ml_d": float(gompertz[1]),
                "gompertz_lag_d": float(gompertz[2]),
            }
        )
    metrics = pd.DataFrame(treatment_metrics)
    for axis, indices in metrics.groupby("experiment_axis").groups.items():
        control = metrics.loc[indices].query("treatment == 'control'").iloc[0]
        metrics.loc[indices, "final_vs_control_pct"] = 100 * (
            metrics.loc[indices, "final_methane_ml"] / control["final_methane_ml"] - 1
        )
        metrics.loc[indices, "day10_vs_control_pct"] = 100 * (
            metrics.loc[indices, "day10_methane_ml"] / control["day10_methane_ml"] - 1
        )
        metrics.loc[indices, "gompertz_rate_vs_control_pct"] = 100 * (
            metrics.loc[indices, "gompertz_rate_ml_d"] / control["gompertz_rate_ml_d"] - 1
        )
        metrics.loc[indices, "t90_change_vs_control_d"] = (
            metrics.loc[indices, "observed_t90_d"] - control["observed_t90_d"]
        )
    comparison = pd.DataFrame(comparisons)
    comparison["aicc_rank"] = comparison.groupby(
        ["experiment_axis", "treatment"]
    )["aicc"].rank(method="min")
    return metrics, comparison


def process_metrics(process: pd.DataFrame) -> pd.DataFrame:
    vfa = process.loc[process["measurement"] == "vfa"].copy()
    ph = process.loc[process["measurement"] == "ph"].copy()
    totals = (
        vfa.groupby(["experiment_axis", "treatment", "time_days"], as_index=False)[
            "value"
        ]
        .sum()
        .rename(columns={"value": "total_vfa_mg_l"})
    )
    ph_metrics = ph.groupby(
        ["experiment_axis", "treatment"], as_index=False
    ).agg(min_ph=("value", "min"), final_ph=("value", "last"))
    wide = totals.pivot(
        index=["experiment_axis", "treatment"],
        columns="time_days",
        values="total_vfa_mg_l",
    ).reset_index()
    wide.columns = [
        str(column)
        if isinstance(column, str)
        else f"total_vfa_day{int(column)}_mg_l"
        for column in wide.columns
    ]
    result = wide.merge(ph_metrics, on=["experiment_axis", "treatment"], how="left")
    for axis, indices in result.groupby("experiment_axis").groups.items():
        control = result.loc[indices].query("treatment == 'control'").iloc[0]
        for day in (6, 12, 18):
            column = f"total_vfa_day{day}_mg_l"
            result.loc[indices, f"vfa_day{day}_vs_control_pct"] = 100 * (
                result.loc[indices, column] / control[column] - 1
            )
    return result


def biochar_correlations(
    metrics: pd.DataFrame, process: pd.DataFrame, characteristics: pd.DataFrame
) -> pd.DataFrame:
    kinetics = metrics.loc[metrics["experiment_axis"] == "pyrolysis_temperature"]
    processes = process.loc[process["experiment_axis"] == "pyrolysis_temperature"]
    merged = characteristics.merge(kinetics, on="treatment").merge(
        processes, on=["experiment_axis", "treatment"]
    )
    pairs = {
        "surface_o_c_vs_gompertz_rate": ("surface_o_c_ratio_xps", "gompertz_rate_ml_d"),
        "raman_id_ig_vs_gompertz_rate": ("raman_id_ig_ratio", "gompertz_rate_ml_d"),
        "day12_vfa_vs_gompertz_rate": ("total_vfa_day12_mg_l", "gompertz_rate_ml_d"),
    }
    rows = []
    for name, (left, right) in pairs.items():
        x = merged[left].to_numpy(float)
        y = merged[right].to_numpy(float)
        pearson = pearsonr(x, y)
        spearman = spearmanr(x, y)
        leave_one_out = [
            pearsonr(np.delete(x, i), np.delete(y, i)).statistic
            for i in range(len(x))
        ]
        rows.append(
            {
                "relationship": name,
                "n": len(x),
                "pearson_r": pearson.statistic,
                "pearson_r2": pearson.statistic**2,
                "pearson_p": pearson.pvalue,
                "spearman_rho": spearman.statistic,
                "loo_pearson_min": min(leave_one_out),
                "loo_pearson_max": max(leave_one_out),
                "interpretation": "exploratory_small_n_not_causal",
            }
        )
    return pd.DataFrame(rows)


def _plot_methane(methane: pd.DataFrame, output: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(13, 5), sharey=True)
    for axis, plot_axis in zip(("pyrolysis_temperature", "pyrolysis_duration"), axes, strict=True):
        subset = methane.loc[methane["experiment_axis"] == axis]
        for treatment, frame in subset.groupby("treatment"):
            frame = frame.sort_values("time_days")
            plot_axis.plot(
                frame["time_days"],
                frame["cumulative_methane_ml"],
                marker="o",
                ms=3,
                label=treatment.replace("biochar_", ""),
            )
        plot_axis.set_title(axis.replace("_", " ").title())
        plot_axis.set_xlabel("Digestion time (d)")
        plot_axis.grid(alpha=0.2)
    axes[0].set_ylabel("Cumulative methane (mL per bottle)")
    axes[1].legend(fontsize=8, frameon=False)
    fig.tight_layout()
    fig.savefig(output, dpi=200)
    plt.close(fig)


def analyze(
    methane_path: Path,
    process_path: Path,
    characteristics_path: Path,
    output: Path,
) -> dict[str, object]:
    output.mkdir(parents=True, exist_ok=True)
    methane = pd.read_csv(methane_path)
    process = pd.read_csv(process_path)
    characteristics = pd.read_csv(characteristics_path)
    metrics, models = kinetic_metrics(methane)
    processes = process_metrics(process)
    correlations = biochar_correlations(metrics, processes, characteristics)
    metrics.to_csv(output / "zhang_treatment_metrics.csv", index=False)
    models.to_csv(output / "zhang_model_comparison.csv", index=False)
    processes.to_csv(output / "zhang_process_metrics.csv", index=False)
    correlations.to_csv(output / "zhang_exploratory_correlations.csv", index=False)
    _plot_methane(methane, output / "zhang_methane_kinetics.png")
    best = metrics.query(
        "experiment_axis == 'pyrolysis_temperature' "
        "and treatment == 'biochar_750c_60min'"
    ).iloc[0]
    summary = {
        "study": "Zhang et al. (2022)",
        "source_doi": "10.1007/s42773-022-00187-6",
        "primary_finding": (
            "biochar_750c_60min accelerates methane kinetics and VFA clearance "
            "with little endpoint-yield change"
        ),
        "b750_60": {
            "final_vs_control_pct": best["final_vs_control_pct"],
            "day10_vs_control_pct": best["day10_vs_control_pct"],
            "gompertz_rate_vs_control_pct": best[
                "gompertz_rate_vs_control_pct"
            ],
            "t90_change_vs_control_d": best["t90_change_vs_control_d"],
        },
        "limitations": [
            "consolidated means only",
            "original triplicates unavailable",
            "no reactor-held-out validation",
            "correlations use five temperature treatments and are exploratory",
        ],
    }
    (output / "zhang_analysis_summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--methane", type=Path, required=True)
    parser.add_argument("--process", type=Path, required=True)
    parser.add_argument("--characteristics", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("results/private/zhang_2022"))
    args = parser.parse_args()
    print(
        json.dumps(
            analyze(args.methane, args.process, args.characteristics, args.output),
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
